from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List

from detection.hybrid_detector import SignatureDetector, SignatureResult

logger = logging.getLogger("zyder.detection.suricata")


class SuricataDetector(SignatureDetector):
    """
    Adapter between Suricata EVE JSON alerts and ZYDER's
    SignatureDetector interface.
    
    Parses EVE JSON once upon initialization to optimize flow lookups.
    """

    def __init__(self, eve_log: str) -> None:
        self.eve_log = Path(eve_log)
        self.alerts = []
        self._parse_log()

    def _parse_log(self) -> None:
        if not self.eve_log.exists():
            logger.warning(f"Suricata EVE log not found: {self.eve_log}")
            return
            
        with self.eve_log.open("r") as f:
            for line in f:
                line = line.strip()
                if not line: continue
                try:
                    event = json.loads(line)
                except json.JSONDecodeError:
                    continue

                if event.get("event_type") != "alert":
                    continue
                    
                alert = event.get("alert", {})
                signature = alert.get("signature", "")
                if "invalid checksum" in signature.lower():
                    continue
                    
                self.alerts.append({
                    "src_ip": event.get("src_ip"),
                    "dst_ip": event.get("dest_ip"),
                    "src_port": event.get("src_port"),
                    "dst_port": event.get("dest_port"),
                    "signature": signature,
                    "signature_id": alert.get("signature_id", "unknown"),
                    "severity": int(alert.get("severity", 3))
                })

    def detect(self, flow: Dict[str, Any]) -> SignatureResult:
        """
        Match the pre-parsed Suricata alerts against the supplied flow.
        """
        if not self.alerts:
            return SignatureResult(
                is_intrusion=False,
                matched_rules=[],
                severity="NONE",
                engine="suricata",
                details="No alerts generated by Suricata."
            )

        src_ip = flow.get("src_ip", flow.get("source_ip", None))
        dst_ip = flow.get("dst_ip", flow.get("destination_ip", None))
        src_port = flow.get("src_port", flow.get("source_port", None))
        dst_port = flow.get("dst_port", flow.get("destination_port", None))

        matched_rules = []
        highest_severity = 0
        matched_details = []

        for e in self.alerts:
            match_forward = True
            match_reverse = True
            
            if src_ip is not None:
                if e["src_ip"] != src_ip: match_forward = False
                if e["dst_ip"] != src_ip: match_reverse = False
            if dst_ip is not None:
                if e["dst_ip"] != dst_ip: match_forward = False
                if e["src_ip"] != dst_ip: match_reverse = False
            if src_port is not None:
                if e["src_port"] != src_port: match_forward = False
                if e["dst_port"] != src_port: match_reverse = False
            if dst_port is not None:
                if e["dst_port"] != dst_port: match_forward = False
                if e["src_port"] != dst_port: match_reverse = False
                
            if not (match_forward or match_reverse):
                continue
                
            matched_rules.append(f"SID-{e['signature_id']}: {e['signature']}")
            matched_details.append(f"{e['signature']} (SID {e['signature_id']})")
            highest_severity = max(highest_severity, e["severity"])

        if matched_rules:
            if highest_severity == 1: zyder_severity = "CRITICAL"
            elif highest_severity == 2: zyder_severity = "HIGH"
            else: zyder_severity = "MEDIUM"

            return SignatureResult(
                is_intrusion=True,
                matched_rules=matched_rules,
                severity=zyder_severity,
                engine="suricata",
                details="Suricata detected: " + ", ".join(matched_details),
            )

        return SignatureResult(
            is_intrusion=False,
            matched_rules=[],
            severity="NONE",
            engine="suricata",
            details="No matching Suricata alerts found.",
        )
